### ISSUE TITLE
Enhance Menu Items

### ISSUE THREAD

**Issue by Sam-Varghese** [Sam-Varghese/Technex-2022-Wbsite#5]
Currently when we hover over menu bar, then it shows the regular cursor meant to select text. I want somebody to change the cursor type of the menu items.

![image](https://user-images.githubusercontent.com/79152648/150337018-169e26b6-edae-452d-abdb-3ea55b8043e3.png)

**Comment by Mahad410** [comment]
I want to contribute to your project so I want you to believe in me.

**Comment by nhlmg93** [comment]
what do you mean change the cursor type of the menu items?
